### ISSUE TITLE
ACEmulator server won't start

### ISSUE THREAD

**Issue by Brumphry** [ACEmulator/ACE-PCAP-Exports#75]
Everything went well up until it came time to actually start the server with ACE.Server.exe. Window pops up, stuff scrolls by, the window fills with lines of red text then closes.

I'm by no means a code guy. I do see several lines that say "Access denied for user" I went back through MySQL and made sure username and password were correct.

Any help would be appreciated. Just want to take a trip down memory lane on my own server

Here is the log:

2020-04-02 17:37:12,036 [1] INFO  (ACE.Server.Program) Starting ACEmulator...
2020-04-02 17:37:12,144 [1] INFO  (ACE.Server.Program) Initializing ConfigManager...
2020-04-02 17:37:12,785 [1] INFO  (ACE.Server.Program) Initializing ServerManager...
2020-04-02 17:37:12,785 [1] INFO  (ACE.Server.Program) Initializing DatManager...
2020-04-02 17:37:17,995 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_cell_1.dat file, containing 805348 records
2020-04-02 17:37:18,598 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_portal.dat file, containing 79694 records
2020-04-02 17:37:18,608 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_local_English.dat file, containing 118 records
2020-04-02 17:37:18,608 [1] INFO  (ACE.Server.Program) Initializing DatabaseManager...
2020-04-02 17:37:20,217 [1] ERROR (ACE.Server.Program) MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists()
   at ACE.Database.AuthenticationDatabase.Exists(Boolean retryUntilFound) in C:\ACE-master\Source\ACE.Database\AuthenticationDatabase.cs:line 28
   at ACE.Database.DatabaseManager.Initialize(Boolean autoRetry) in C:\ACE-master\Source\ACE.Database\DatabaseManager.cs:line 24
   at ACE.Server.Program.Main(String[] args) in C:\ACE-master\Source\ACE.Server\Program.cs:line 175
2020-04-02 17:39:45,880 [1] INFO  (ACE.Server.Program) Starting ACEmulator...
2020-04-02 17:39:45,908 [1] INFO  (ACE.Server.Program) Initializing ConfigManager...
2020-04-02 17:39:46,050 [1] INFO  (ACE.Server.Program) Initializing ServerManager...
2020-04-02 17:39:46,050 [1] INFO  (ACE.Server.Program) Initializing DatManager...
2020-04-02 17:39:46,932 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_cell_1.dat file, containing 805348 records
2020-04-02 17:39:47,056 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_portal.dat file, containing 79694 records
2020-04-02 17:39:47,059 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_local_English.dat file, containing 118 records
2020-04-02 17:39:47,059 [1] INFO  (ACE.Server.Program) Initializing DatabaseManager...
2020-04-02 17:39:47,771 [1] ERROR (ACE.Server.Program) MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists()
   at ACE.Database.AuthenticationDatabase.Exists(Boolean retryUntilFound) in C:\ACE-master\Source\ACE.Database\AuthenticationDatabase.cs:line 28
   at ACE.Database.DatabaseManager.Initialize(Boolean autoRetry) in C:\ACE-master\Source\ACE.Database\DatabaseManager.cs:line 24
   at ACE.Server.Program.Main(String[] args) in C:\ACE-master\Source\ACE.Server\Program.cs:line 175
2020-04-02 17:46:18,971 [1] INFO  (ACE.Server.Program) Starting ACEmulator...
2020-04-02 17:46:19,006 [1] INFO  (ACE.Server.Program) Initializing ConfigManager...
2020-04-02 17:46:19,148 [1] INFO  (ACE.Server.Program) Initializing ServerManager...
2020-04-02 17:46:19,148 [1] INFO  (ACE.Server.Program) Initializing DatManager...
2020-04-02 17:46:20,019 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_cell_1.dat file, containing 805348 records
2020-04-02 17:46:20,141 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_portal.dat file, containing 79694 records
2020-04-02 17:46:20,144 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_local_English.dat file, containing 118 records
2020-04-02 17:46:20,144 [1] INFO  (ACE.Server.Program) Initializing DatabaseManager...
2020-04-02 17:46:20,855 [1] ERROR (ACE.Server.Program) MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists()
   at ACE.Database.AuthenticationDatabase.Exists(Boolean retryUntilFound) in C:\ACE-master\Source\ACE.Database\AuthenticationDatabase.cs:line 28
   at ACE.Database.DatabaseManager.Initialize(Boolean autoRetry) in C:\ACE-master\Source\ACE.Database\DatabaseManager.cs:line 24
   at ACE.Server.Program.Main(String[] args) in C:\ACE-master\Source\ACE.Server\Program.cs:line 175
2020-04-02 17:51:22,325 [1] INFO  (ACE.Server.Program) Starting ACEmulator...
2020-04-02 17:51:22,353 [1] INFO  (ACE.Server.Program) Initializing ConfigManager...
2020-04-02 17:51:22,494 [1] INFO  (ACE.Server.Program) Initializing ServerManager...
2020-04-02 17:51:22,495 [1] INFO  (ACE.Server.Program) Initializing DatManager...
2020-04-02 17:51:23,364 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_cell_1.dat file, containing 805348 records
2020-04-02 17:51:23,489 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_portal.dat file, containing 79694 records
2020-04-02 17:51:23,492 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_local_English.dat file, containing 118 records
2020-04-02 17:51:23,492 [1] INFO  (ACE.Server.Program) Initializing DatabaseManager...
2020-04-02 17:51:24,196 [1] ERROR (ACE.Server.Program) MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists()
   at ACE.Database.AuthenticationDatabase.Exists(Boolean retryUntilFound) in C:\ACE-master\Source\ACE.Database\AuthenticationDatabase.cs:line 28
   at ACE.Database.DatabaseManager.Initialize(Boolean autoRetry) in C:\ACE-master\Source\ACE.Database\DatabaseManager.cs:line 24
   at ACE.Server.Program.Main(String[] args) in C:\ACE-master\Source\ACE.Server\Program.cs:line 175
2020-04-02 18:00:36,371 [1] INFO  (ACE.Server.Program) Starting ACEmulator...
2020-04-02 18:00:36,400 [1] INFO  (ACE.Server.Program) Initializing ConfigManager...
2020-04-02 18:00:36,583 [1] INFO  (ACE.Server.Program) Initializing ServerManager...
2020-04-02 18:00:36,583 [1] INFO  (ACE.Server.Program) Initializing DatManager...
2020-04-02 18:00:37,462 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_cell_1.dat file, containing 805348 records
2020-04-02 18:00:37,583 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_portal.dat file, containing 79694 records
2020-04-02 18:00:37,586 [1] INFO  (ACE.DatLoader.DatManager) Successfully opened c:\ACE\Dats\client_local_English.dat file, containing 118 records
2020-04-02 18:00:37,586 [1] INFO  (ACE.Server.Program) Initializing DatabaseManager...
2020-04-02 18:00:38,411 [1] ERROR (ACE.Server.Program) MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'ACEmu'@'%' to database 'ace_auth'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 125
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 338
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 63
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 227
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 75
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlDatabaseCreator.Exists()
   at ACE.Database.AuthenticationDatabase.Exists(Boolean retryUntilFound) in C:\ACE-master\Source\ACE.Database\AuthenticationDatabase.cs:line 28
   at ACE.Database.DatabaseManager.Initialize(Boolean autoRetry) in C:\ACE-master\Source\ACE.Database\DatabaseManager.cs:line 24
   at ACE.Server.Program.Main(String[] args) in C:\ACE-master\Source\ACE.Server\Program.cs:line 175

**Comment by Brumphry** [comment]
Fixed.
